### ISSUE TITLE
Development or Death ?

### ISSUE THREAD

**Issue by MadTooth** [hatoving/PonyIsland#2]
![2022-12-17-194242](https://user-images.githubusercontent.com/30464341/208920770-12a52a8e-6c76-45b5-bb23-eb80283d9b83.jpg)
>[Message written using machine translation]

### Pony Island PsVita [Port]

1. **Version v1.22 != v1.20**

_To create modified files, I used "Pony Island v1.22", but the result is v1.20 ! (Missing: Russian Language)_

2. **Low performance**

_The game works with insufficient performance! But what I see and appreciate is that the game is not maximum PsVita performance_

3. **My game suggestion**

_Interaction with "game details" does not work everywhere! (Example: In "code execution", moving "arrows/cycles" with the cross button does not work)_

### **_CAN YOU IMPROVE/FIX YOUR MOD?_**

**[Addition]**

- I see that you are working on various projects to port games to PsVita

**MY QUESTIONS:**

- How do you port a game to PsVita ? (Maybe you will make an Instruction for everyone who wants to develop the "world" of PsVita)

- Do you have other PsVita porting plans in the future? (I want a PsVita port of Dead Cells)

**[My recommendations]**

- Add contact details in your "GitHub - Profile", it's inconvenient to quickly "communicate" through "GitHub - Issue"

**Comment by hatoving** [comment]
- i might one day update the game to version 1.22 but i don't have any plans right now as i'm focusing on my own personal shiz.
- if you're having performance issues, use an overclocking plugin, i believe that's literally in the readme too if you have even read it
- i have no idea what's wrong here. it works completely fine for me. maybe some plugin is fucking things up?
- you can learn c/c++ first and build some simple apps with sdl2, or, if you're not willing to do that, gamemaker is a viable option too. unity ain't a bad choice either ig
- dead cells is literally impossible cuz it would prolly go out of memory the instant the vita tries to boot it up

**Comment by MadTooth** [comment]
Understood.
